typography_spectrum: 0.6195593711454421
color:
  brandColors:
    - '#e47c68'
    - '#469082'
    - '#ffffff'
    - '#000000'
    - '#ff0000'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9066811176016927
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8978c6e3-aa1b-4bbd-be69-0d2754cf1841.png
name: Digital Tales
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/19b45456-7fde-4dd5-a66f-cc36b1821138.png
title: Digital Tales - Audiobook Production
purpose: []
