layout_spectrum: 0.8845714293420315
typography_spectrum: 0.23999198013916612
color:
  brandColors:
    - '#e47c68'
    - '#469082'
    - '#ffffff'
    - '#000000'
    - '#ff0000'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
name: Digital Tales
favicon: null
title: Digital Tales - Audiobook Production & Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
