typography_spectrum: 0.6195593711454421
color:
  brandColors:
    - '#e47c68'
    - '#469082'
    - '#ffffff'
    - '#000000'
    - '#ff0000'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9066811176016927
analytics:
  google: null
  facebook: null
  twitter: null
name: Digital Tales
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Audiobook Production & Marketing
purpose: []
