name: Digital Tales
favicon: null
layout_spectrum: 0.17225
typography_spectrum: 0.4428
title: 'Digital Tales - Audiobook Production & Marketing'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e47c68'
    - '#469082'
    - '#ffffff'
    - '#000000'
    - '#ff0000'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
