layout_spectrum: 0.5975311219226569
typography_spectrum: 0.5229364370461553
color:
  brandColors:
    - '#FEC046'
    - '#469082'
    - '#FFFFFF'
    - '#000000'
    - '#FF0000'
  brandStrength: 0.6636952832341194
  lightness: 0.31283829011954367
  saturation: 0.6101525642443448
  rhythmicContrast: 0.873108608648181
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8978c6e3-aa1b-4bbd-be69-0d2754cf1841.png
name: Digital Tales
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/19b45456-7fde-4dd5-a66f-cc36b1821138.png
title: Digital Tales - Audiobook Production
purpose: []
