name: Digital Tales
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05328
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a202f'
    - '#623c38'
    - '#ca7f55'
    - '#efa76b'
    - '#f6e8de'
  brandStrength: 0.3125
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
