name: Digital Tales
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05328
title: Digital Tales Audiobook Production and eBook Publishing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e47c68'
    - '#469082'
    - '#ffffff'
    - '#000000'
    - '#ff0000'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
